swodlr-ui-unlock-inputs-new: limit inputs to hardcoded limits
podaac/swodlr-ui pull request #33
Opened 2023-08-08 19:51 UTC by jbyrne6

Created a new PR after cleaning up local develop branch. 

### Changes:
- changes to the GranuleTable.tsx file, limiting cycle, scene, and pass to the hardcoded limits.
- fix the download url on the My Data page

2023-08-08 20:02 UTC, joshgarde requested changes

2023-08-09 20:10 UTC, jbyrne6 commented on src/components/sidebar/GranulesTable.tsx
> +    })
The state management system in React and Redux don't play well with storing sets. I am wondering if the volume of added granules are low enough that the forEach loop of addedProducts is fine. I don't think there will ever be more than 100 granules added at a time right?

2023-09-15 00:35 UTC, frankinspace commented on src/components/sidebar/GranulesTable.tsx
> +    })
Don't know how many granules will be typical... could be more than 100. We can table this for now though since it's not a simple fix.

2023-09-15 00:35 UTC, frankinspace approved these changes

2023-09-18 16:49 UTC, closed without merging