feature/swodlr-ui-56: add BrowserRouter
podaac/swodlr-ui pull request #60
Opened 2023-10-25 22:56 UTC by jbyrne6

### Changes
- Changed from HashRouter to BrowserRouter

2023-10-31 16:19 UTC, frankinspace requested changes
When adding granules you get a success message along with multiple error messages. See short clip:

https://github.com/podaac/swodlr-ui/assets/89428916/641ed57b-8d0c-45c5-aff0-9bc581ff6b7e

2023-10-31 16:19 UTC, frankinspace commented on src/components/app/App.tsx
> +      // if (!userAuthenticated) {
Remove commented out code

2023-10-31 16:19 UTC, frankinspace commented on src/components/sidebar/ProductCustomization.tsx
> +        // const newParamsObject: newUrlParamsObject = {}
Remove commented out code

2023-11-01 20:36 UTC, jbyrne6 commented on src/components/sidebar/ProductCustomization.tsx
> +        // const newParamsObject: newUrlParamsObject = {}
done

2023-11-01 20:36 UTC, jbyrne6 commented on src/components/app/App.tsx
> +      // if (!userAuthenticated) {
done

2023-11-01 20:52 UTC, jbyrne6 commented
> When adding granules you get a success message along with multiple error messages. See short clip:
> 
>  adding-granules.mov

Found that the useEffect in the GranuleTable.tsx page was re-rendering on change of the addedProducts redux state variable so removed that re-render condition to solve this incorrect alert issue.

2023-11-02 00:29 UTC, jbyrne6 commented
Bug: noticed that in SIT, the band and zone adjust is not matching on the site what it says in the url. Also look into bug with adding multiple scenes at once with a hyphen

2023-11-13 23:43 UTC, frankinspace approved these changes

2023-11-14 20:15 UTC, merged