Feature/swodlr UI 71 - add pagination to my data page
podaac/swodlr-ui pull request #98
Opened 2024-04-04 17:52 UTC by jbyrne6

Related to ticket #71

2024-04-04 23:30 UTC, joshgarde commented
@jbyrne6 Looks like this needs to be rebased on top of the current develop

2024-04-04 23:31 UTC, joshgarde requested changes
@jbyrne6 Looks like this needs to be rebased on top of the current develop

2024-04-23 13:17 UTC, viviant100 approved these changes

2024-04-23 15:03 UTC, davidcolemanjpl approved these changes

2024-04-23 16:51 UTC, merged